### ISSUE TITLE
ERROR in ./index.js Module build failed: TypeError: template is not a function

### ISSUE THREAD

**Issue by kkseven07** [gaearon/react-hot-loader#1009]
Moved to RHL v4 and got this error. I am  a newbie in react and webpack, so you explain how to fix this? 
Versions:
 "babel": "^6.5.2",
    "babel-cli": "^6.9.0",
    "babel-core": "^5.8.38",
    "babel-loader": "^6.4.1",
    "babel-plugin-transform-runtime": "^6.9.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "webpack": "^1.9.11",

**Comment by theKashey** [comment]
Sorry, my psy abilities are not so strong.
Could you provide a bit more context, source code, error as it is, and so on.

**Comment by kkseven07** [comment]
Updated the issue, what else I should show? Everything worked with RHL 1.2.9, I know that its pretty old version. I added `export default hot(module)(Root)` to my root component according to documentation with v4.

**Comment by theKashey** [comment]
Look like the problem is Babel loader or Babel core. 
Please delete Babel-core, you probably don’t need it, and update Babel-loader.

**Comment by kkseven07** [comment]
It didnt help, babel loader requires installed babel-core. Or is there smth i'm doing wrong?

**Comment by theKashey** [comment]
Look like the problem is babel 5
`
"babel-core": "^5.8.38", <-----
"babel-loader": "^6.4.1", <-----
`
Please use babel-core: 6X, and babel loader 7X

All our tests are using
`
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
`
That is not the "latest" versions, but quite fresh.
