### ISSUE TITLE
"Compare is not a function" when composing React.memo with hocs

### ISSUE THREAD

**Issue by niekert** [gaearon/react-hot-loader#1135]
### Description
Thank you for your work on making `react-hot-loader` compatible with React 16.7! I've tried upgrading an existing project to 16.7 and the latest version of RHL and ran into an issue. 

I've dug into the issue and bit and have found the issue seems to occur when composing a component with `React.memo` and some other HOCs.

### Actual behavior
`react-dom` throws the `Compare is not a function`, seemingly because `Component.compare` is `undefined` instead of `null`?

![image](https://user-images.githubusercontent.com/5508905/50183561-c7ecf280-0312-11e9-9253-c8461a2a3f81.png)

### Expected behavior
Hot reloading works as intended

### Environment

React Hot Loader version: 4.6.2 with `@hot-loader/react-dom` alias. 
Hot reloading worked fine with version `4.0.0`

### Reproducible Demo
Here is a reproducible repo: https://github.com/niekert/rhl-context-memo-issue

The issue occurs when I change [this line](https://github.com/niekert/rhl-context-memo-issue/blob/master/src/CurrentCount.js#L7) in the React component, though it seems to only occur _every other_ change 🤔 

It seems to be also somewhat related to this composed `connect` and `React.memo` [in this component](https://github.com/niekert/rhl-context-memo-issue/blob/master/src/Counter.js).

On the branch `previous-hmr-version` of that repo, `react-hot-loader@4.0.0` is installed. The issue does not occur there.

**Comment by theKashey** [comment]
4.0.0 does not "see" Memo, that's why it working (it's not working at all)

**Comment by niekert** [comment]
Ah that makes sense. Maybe composing hocs with `memo` is a bad idea in general?

The hot reloading of a component that used `memo` in 4.0.0 does seem to work for me. What is the difference now that rhl is "aware" of `React.memo`? :)

**Comment by theKashey** [comment]
Yep. Not it aware, and doing something not expected with it.
I'll fix the problem today, dont worry.

**Comment by theKashey** [comment]
4.6.3 (and actually new hot-loader/react-dom or webpack plugin) would solve the issue

**Comment by niekert** [comment]
Can confirm that it works now 🙏

Thank you for fixing this so quickly!
